prefix = "."
stop-words = "stopwords.txt"

dataset = "corpus"
corpus = "line.toml"
index = "idx"

[[analyzers]]
method = "ngram-word"
ngram = 3
filter = "default-unigram-chain"

[[analyzers]]
method = "ngram-word"
ngram = 2
filter = "default-unigram-chain"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[[analyzers]]
method = "ngram-pos"
ngram = 2
filter = [{type = "icu-tokenizer"}, {type = "ptb-normalizer"}]
crf-prefix = "crf"

